name: mobile1_flutter_coding_test
description: "mobile1_flutter_coding_test"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  #데이터 모델
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  #상태관리
  hooks_riverpod: ^2.4.9
  flutter_hooks: ^0.20.4
  riverpod_annotation: ^2.3.3

  #통신
  dio: ^5.4.0
  retrofit: ^4.4.2

  logger: ^2.0.2+1
  go_router: ^12.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  retrofit_generator: ^9.1.5

flutter:
  uses-material-design: true

  assets:
    - assets/raw_data/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/PretendardVariable.ttf